### ISSUE TITLE
I'm not sure, but it seems that we have a problem with JetWooBuilder

### ISSUE THREAD

**Issue by ho30hero** [peprodev/ultimate-invoice#1]
سلام و درود
امیدوارم که خوب باشید. 
اول از هرچیز تشکر میکنم که یک افزونه حرفه ای را بصورت رایگان در مخزن قرار دادید.  بسیار توانمند و جذاب هست. خدا خیرتون بده ان شاالله و بهترین ها را روزی کنه برای شما و تیم شما.

یک سایت جدید راه اندازی میکردیم که همان اوایل کار با یک پیام خطا مواجه شدیم.
گفتم خدمتتون ارسال کنم ایمیل گزارش خطا را که شما هم در جریان باشید تا اگر از سمت افزونه باشه بررسی و رفع بشه اگر صلاح بود.

پیام هم فکر میکنم هنگامی ارسال میشه که میخواستم دسته بندی پیش فرض محصولات را تغییر نام بدم!! 

ارادتمند
خان محمدی

از وردپرس ۵.۲ ویژگی‌های درونی برای تشخیص اینکه چه موقع یک افزونه یا پوسته در سایت شما دچار خطای مهلک شد، و با این ایمیل خودکار به شما اطلاع دهد، وجود دارد.

در این مورد، وردپرس خطایی با یکی از افزونه‌های شما گرفت، JetWooBuilder.

اول، سایت خود (https://mydomain.ir/) را ببینید و برای هر خطای قابل رویتی بررسی نمایید.
 سپس، برگه‌ای که خطا در ان رخ داد را ببینید (https://mydomain.ir/wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product) و برای هر خطای قابل رویتی بررسی نمایید.

لطفا برای کمک بیشتر درخصوص بررسی این مشکل با میزبان خود تماس بگیرید.

اگر سایت شما با مشکل نمایش داده می‌شود و شما نمی‌توانید بصورت معمول به پیشخوان دسترسی داشته باشید، هم‌اکنون وردپرس دارای یک "حالت ترمیم" ویژه است. این به شما اجازه می‌دهد با خیال راحت وارد پیشخوان خود شوید و بررسی بیشتری نمایید.

https://mydomain.ir/wp-login.php?action=enter_recovery_mode&rm_token=Vzeue8shjSMU6KtSMX7sSe&rm_key=OZIy67pC3ICoSI2l3Tnil2

برای امن نگه‌داشتن سایتتان، این پیوند در 1 روز منقضی می‌شود. بابت آن نگران نباشید، اگرچه: اگر بعد از انقضای آن دوباره خطایی اتفاق بیوفتد یک پیوند جدید به شما ایمیل خواهد شد.

وقتی دنبال کمک برای این مشکل هستید، شاید از شما برخی از اطلاعات زیر پرسیده شود:
نگارش وردپرس 5.6.2
پوسته فعلی: Woodmart Child (نگارش 1.0.0)
افزونه فعلی: JetWooBuilder (نگارش 1.7.6)
PHP نگارش 7.4.14

جزئیات خطا
===================
یک خطا از نوع E_ERROR در خط 127 از پرونده /home/username/public_html/wp-content/plugins/jet-woo-builder/includes/settings/class-jet-woo-builder-shop-settings.php رخ داد. پیام خطا: Uncaught Error: Cannot use object of type PeproUltimateInvoice_WC_Setting as array in /home/username/public_html/wp-content/plugins/jet-woo-builder/includes/settings/class-jet-woo-builder-shop-settings.php:127
Stack trace:
#0 /home/username/public_html/wp-includes/class-wp-hook.php(287): Jet_Woo_Builder_Shop_Settings->register_woo_settings_page(Object(PeproUltimateInvoice_WC_Setting))
#1 /home/username/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(Object(PeproUltimateInvoice_WC_Setting), Array)
#2 /home/username/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(62): apply_filters('woocommerce_get...', Array)
#3 /home/username/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(175): WC_Admin_Settings::get_settings_pages()
#4 /home/username/public_html/wp-includes/class-wp-hook.php(287): WC_API->register_wp_admin_settings(Object(WP_REST_Server))
#5 /home/username/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, A

**Comment by ho30hero** [comment]
سلام مجدد
بنظرم میرسه که مشکل از خود پلاگین 
JetWooBuilder 
هست. 

وقتی فعال میشه روی تم "وودمارت"، لینک های "ویرایش سریع از کار میفتند و یا خطا میدهند. 
و هیچ مشکلی از سمت افزونه شما نیست. 

در هر صورت باز هم ممنون از شما. باید بیشتر بررسی میکردم قبل از ارسال پیام.

ان شاالله که همواره موفق باشید .
ارادتمند

**Comment by amirhosseinhpv** [comment]
**سلام.**
متشکریم از انتخاب ما و ابراز محبت تون، لطف دارید شما

اگر مورد دیگه ای مشاهده شد لطفا اطلاع بدید تا در اولین فرصت برطرف شود

_-- حسین پور، بخش فنی_

**Comment by ho30hero** [comment]
سلام مجدد
باعث خوشحالی خواهد بود اگر بتونیم کمک کنیم در بهتر شدن کار شما که کار خود ما هم هست به نحوی.

چون مجددا برخورد کردم به مسئله مشابه، مجددا براتون ارسال میکنم پیام خطا را، فکر میکنم شما هم یک نگاهی بندازید بد نباشه. 
این متن پیام خطایی هست که ایمیل شده از وردپرس به ما:

درود،

از وردپرس ۵.۲ ویژگی‌های درونی برای تشخیص اینکه چه موقع یک افزونه یا پوسته در سایت شما دچار خطای مهلک شد، و با این ایمیل خودکار به شما اطلاع دهد، وجود دارد.

در این مورد، وردپرس خطایی با یکی از افزونه‌های شما گرفت، JC WooCommerce Advanced Attributes.

اول، سایت خود (https://domain.com/) را ببینید و برای هر خطای قابل رویتی بررسی نمایید.
 سپس، برگه‌ای که خطا در ان رخ داد را ببینید (https://domain.com/wp-admin/edit.php?post_type=product) و برای هر خطای قابل رویتی بررسی نمایید.

لطفا برای کمک بیشتر درخصوص بررسی این مشکل با میزبان خود تماس بگیرید.

اگر سایت شما با مشکل نمایش داده می‌شود و شما نمی‌توانید بصورت معمول به پیشخوان دسترسی داشته باشید، هم‌اکنون وردپرس دارای یک "حالت ترمیم" ویژه است. این به شما اجازه می‌دهد با خیال راحت وارد پیشخوان خود شوید و بررسی بیشتری نمایید.

https://domain.com/wp-login.php?action=enter_recovery_mode&rm_token=vtW5VaGrjw3Pvi4RDslbFi&rm_key=dYOFxORqexcOvw3a6CzZkq

برای امن نگه‌داشتن سایتتان، این پیوند در 1 روز منقضی می‌شود. بابت آن نگران نباشید، اگرچه: اگر بعد از انقضای آن دوباره خطایی اتفاق بیوفتد یک پیوند جدید به شما ایمیل خواهد شد.

وقتی دنبال کمک برای این مشکل هستید، شاید از شما برخی از اطلاعات زیر پرسیده شود:
نگارش وردپرس 5.6.2
پوسته فعلی: Newkala Child (نگارش 1.0)
افزونه فعلی: JC WooCommerce Advanced Attributes (نگارش 3.2)
PHP نگارش 7.4.14



جزئیات خطا
===================
یک خطا از نوع E_ERROR در خط 31 از پرونده /home/user/public_html/wp-content/plugins/jc-woocommerce-advanced-attributes/libs/admin/jcaa-admin-init.php رخ داد. پیام خطا: Uncaught Error: Cannot use object of type PeproUltimateInvoice_WC_Setting as array in /home/user/public_html/wp-content/plugins/jc-woocommerce-advanced-attributes/libs/admin/jcaa-admin-init.php:31
Stack trace:
#0 /home/user/public_html/wp-includes/class-wp-hook.php(287): jcaa_register_settings(Object(PeproUltimateInvoice_WC_Setting))
#1 /home/user/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(Object(PeproUltimateInvoice_WC_Setting), Array)
#2 /home/user/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(62): apply_filters('woocommerce_get...', Array)
#3 /home/user/public_html/wp-content/plugins/woocommerce/includes/class-wc-api.php(175): WC_Admin_Settings::get_settings_pages()
#4 /home/user/public_html/wp-includes/class-wp-hook.php(287): WC_API->register_wp_admin_settings(Object(WP_REST_Server))
#5 /home/user/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#6 /home/user/public_html/wp-inclu

**Comment by amirhosseinhpv** [comment]
به نظر میرسه افزونه های دیگه وبسایت شما با نسخه آخر ووکامرس سازگار نباشند. در این رابطه ما نسخه جدیدتری از افزونه فاکتور ووکامرس رو منتشر کردیم که امروز در مخزن بروزرسانی میشود. لطفا آپدیت کنید و اگر بازم مشکی بود در همین ایشو مطرح کنید یا به ایمیل support@pepro.dev پیام ارسال کنید تا همکارانم شما رو راهنمایی کنند . 

_متشکرم._
-- حسین پور، بخش فنی
