### ISSUE TITLE
No administrator rules

### ISSUE THREAD

**Issue by mmojadad** [peprodev/ultimate-invoice#2]
Hi
The plugin have issue with Advanced Access Manager plugin. Just work with Administrator rule and the following address with return Access is denied for all other rules.

yoursite.com/wp-admin/admin.php?page=wc-settings&tab=pepro_ultimate_invoice

**Comment by amirhosseinhpv** [comment]
Hi @mmojadad ,
Please point out to the access management plugin you are using.
