### ISSUE TITLE
Under defined array error

### ISSUE THREAD

**Issue by Reza-nzm** [peprodev/ultimate-invoice#2]
سلام. وقت بخیر 
ببخشید برای مشاهده و دانلود فاکتور یا برچسب پستی با خطای زیر مواجه می شوم.
![Screenshot 2024-10-30 202042](https://github.com/user-attachments/assets/01510767-bab3-4ca6-8fe5-45928bbdb27e)

**Comment by amirhp-com** [comment]
سلام
دیباگ سایت را ببندید

قبل از خروجی پی دی اف چیز دیگری چاپ میشود که احتمالا خطایی هست از افزونه ها یا سایت شما . 

دیباگ را off کنید و مجدد تلاش کنید.
