### ISSUE TITLE
 ADD TAG ORDER

### ISSUE THREAD

**Issue by ArmandoFiore** [peprodev/ultimate-invoice#3]
Hi I’m trying to add the order tags with which my orders are marked.

Plug-in This: [LINK](https://woocommerce.com/it-it/products/order-tags/)

this plugin allows you to insert order tags or labels to define the order.
I would like to add these labels on the order template I print

the code I wrote did not work, my skills did not lead to write a code that allows me to obtain the result I want.
```php
add_filter( "puiw_printinvoice_create_html_item_row_metas", "my_custom_lineitems_macros", 10, 5);
function my_custom_lineitems_macros ($macros, $item_id, $item, $product_id, $order){
	$product = $item->get_product();
	$order_tag = wcot_order_tags_get_order_tags( $order_id );
	$macros["order_tag"] = $order_tag;
	return $macros;
}
```

**Comment by ArmandoFiore** [comment]
It won't let me add the code, I'm getting a syntax error in line 15

**Comment by amirhp-com** [comment]
semicolon is missed at the end of the line.

**Comment by ArmandoFiore** [comment]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function prefix_get_order_tags_html(), 0 passed in /home/customer/www/93street.it/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(484) : eval()'d code on line 5 and exactly 1 expected in /home/customer/www/93street.it/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(484) : eval()'d code:20 Stack trace: #0 /home/customer/www/93street.it/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(484) : eval()'d code(5): prefix_get_order_tags_html() #1 /home/customer/www/93street.it/public_html/wp-includes/class-wp-hook.php(307): {closure}(Array, Object(Automattic\WooCommerce\Admin\Overrides\Order)) #2 /home/customer/www/93street.it/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array) #3 /home/customer/www/93street.it/public_html/wp-content/plugins/pepro-ultimate-invoice/include/admin/class-print.php(301): apply_filters('puiw_get_defaul...', Array, Object(Automattic\WooCommerce\Admin\Overrides\Order) in /home/customer/www/93street.it/public_html/wp-content/plugins/code-snippets/php/snippet-ops.php(484) : eval()'d code on line 20

**Comment by ArmandoFiore** [comment]
when i try to print the html version of the order i get this error

**Comment by amirhp-com** [comment]
```php
add_filter( "puiw_get_default_dynamic_params", function ($macros, $order){
	$macros["order_tag"] = prefix_get_order_tags_html($order->get_id());
	return $macros;
}, 10, 2);
```

**Comment by ArmandoFiore** [comment]
It works perfectly thank you very much, you were very kind

**Comment by amirhp-com** [comment]
You are welcome. We would be really happy if you give us a [five-star rating](https://wordpress.org/support/plugin/pepro-ultimate-invoice/reviews/#new-post). Thank you.

**Comment by amirhp-com** [comment]
I'm okay, please go ahead.

**Comment by amirhp-com** [comment]
You can add custom CSS (something like following code ) in Setting ~> Custom CSS: 
**wp-admin/admin.php?page=wc-settings&tab=pepro_ultimate_invoice&section=theme**
```css
td[if="show_product_image"] img, 
td[class="show_product_image"] img {
	width: 80px;
}
```

**Comment by ArmandoFiore** [comment]
Unfortunately this does not solve the problem

**Comment by amirhp-com** [comment]
I've checked the code, it works for me. 
Try this: 

```css
table.content-table th.show_product_image,
table.content-table td[if="show_product_image"] img, 
table.content-table td[class="show_product_image"] img {
	width: 200px !important;
}
```

**Comment by ArmandoFiore** [comment]
https://ibb.co/W5bnDMn - LINK IMAGE
https://ibb.co/30HC5qp - LINK IMAGE

Unfortunately this didn't work for me, as you can see from the pictures you can see the difference in quality a lot.
I also tried adding max-width as a value, but that didn't work either

**Comment by amirhp-com** [comment]
I should have access to your site so I could debug this issue because I cannot reproduce it. Please create a user in administrator level with email: support@peprodev.com. And check the notify user checkbox so I could log into your shop. Thank you.

**Comment by ArmandoFiore** [comment]
Done, thank you very much for the support

**Comment by amirhp-com** [comment]
> Done, thank you very much for the support

Hi again, I've checked your site and it seems it's okay!
![image](https://user-images.githubusercontent.com/18598809/177477577-aede7e16-60d7-4b40-b817-86d015e4d779.png)
