### ISSUE TITLE
problem with HPOS

### ISSUE THREAD

**Issue by JamesMacMan** [peprodev/ultimate-invoice#5]
Hey
In the new version of WooCommerce, when we activate the HPOS mode, the invoice pdf column is removed in orders section and we can no longer create a PDF invoice in the orders section.

**Comment by babdali91** [comment]
Please put a check box under the pdf label print button so that by selecting it, the user's order note will be printed under the pdf label.  At the same time, with the activation of the new WooCommerce feature, this plugin will be disabled
